[package]
name = "seating-gui-egui"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
eframe = { workspace = true, features = ["glow", "default_fonts", "x11", "wayland"] }
rfd.workspace = true
seating-core = { path = "../seating-core" }

[build-dependencies]
winresource = { workspace = true }
